# Generated by Django 3.2 on 2021-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0004_auto_20210408_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
