# Generated by Django 3.2 on 2021-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0008_video_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_ids', models.JSONField()),
            ],
        ),
    ]
